
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 405)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_chonThuMucAnh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_chonThuMucAnh.setGeometry(QtCore.QRect(20, 10, 141, 31))
        self.btn_chonThuMucAnh.setObjectName("btn_chonThuMucAnh")
        self.lb_dongDanThuMuc = QtWidgets.QLabel(self.centralwidget)
        self.lb_dongDanThuMuc.setGeometry(QtCore.QRect(170, 20, 261, 16))
        self.lb_dongDanThuMuc.setObjectName("lb_dongDanThuMuc")
        self.lb_soAnh = QtWidgets.QLabel(self.centralwidget)
        self.lb_soAnh.setGeometry(QtCore.QRect(20, 40, 161, 16))
        self.lb_soAnh.setObjectName("lb_soAnh")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 92, 561, 271))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_doiTenFile = QtWidgets.QPushButton(self.widget)
        self.btn_doiTenFile.setObjectName("btn_doiTenFile")
        self.verticalLayout.addWidget(self.btn_doiTenFile)
        
        self.btn_giamDungLuongAnh = QtWidgets.QPushButton(self.widget)
        self.btn_giamDungLuongAnh.setObjectName("btn_giamDungLuongAnh")
        self.verticalLayout.addWidget(self.btn_giamDungLuongAnh)
        
        self.btn_tangGiamNhieu = QtWidgets.QPushButton(self.widget)
        self.btn_tangGiamNhieu.setObjectName("btn_tangGiamNhieu")
        self.verticalLayout.addWidget(self.btn_tangGiamNhieu)
        self.btn_doiDinhDang = QtWidgets.QPushButton(self.widget)
        self.btn_doiDinhDang.setObjectName("btn_doiDinhDang")
        self.verticalLayout.addWidget(self.btn_doiDinhDang)
        self.btn_tangGiamSang = QtWidgets.QPushButton(self.widget)
        self.btn_tangGiamSang.setObjectName("btn_tangGiamSang")
        self.verticalLayout.addWidget(self.btn_tangGiamSang)
        self.btn_doiCoAnh = QtWidgets.QPushButton(self.widget)
        self.btn_doiCoAnh.setObjectName("btn_doiCoAnh")
        self.verticalLayout.addWidget(self.btn_doiCoAnh)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_chuanHoaAnh = QtWidgets.QPushButton(self.widget)
        self.btn_chuanHoaAnh.setObjectName("btn_chuanHoaAnh")
        self.verticalLayout_2.addWidget(self.btn_chuanHoaAnh)
        self.btn_tangGiamTuongPhan = QtWidgets.QPushButton(self.widget)
        self.btn_tangGiamTuongPhan.setObjectName("btn_tangGiamTuongPhan")
        self.verticalLayout_2.addWidget(self.btn_tangGiamTuongPhan)
        
        self.btn_tangGiamNet = QtWidgets.QPushButton(self.widget)
        self.btn_tangGiamNet.setObjectName("btn_tangGiamNet")
        self.verticalLayout_2.addWidget(self.btn_tangGiamNet)
        
        self.btn_doiHeMau = QtWidgets.QPushButton(self.widget)
        self.btn_doiHeMau.setObjectName("btn_doiHeMau")
        self.verticalLayout_2.addWidget(self.btn_doiHeMau)
        self.btn_thuPhongAnh = QtWidgets.QPushButton(self.widget)
        self.btn_thuPhongAnh.setObjectName("btn_thuPhongAnh")
        self.verticalLayout_2.addWidget(self.btn_thuPhongAnh)
        self.btn_xoaiNghienAnh = QtWidgets.QPushButton(self.widget)
        self.btn_xoaiNghienAnh.setObjectName("btn_xoaiNghienAnh")
        self.verticalLayout_2.addWidget(self.btn_xoaiNghienAnh)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 584, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_chonThuMucAnh.setText(_translate("MainWindow", "Chọn thư mục chứa ảnh"))
        self.lb_dongDanThuMuc.setText(_translate("MainWindow", "Đường dẫn thư mục chứa ảnh"))
        self.lb_soAnh.setText(_translate("MainWindow", "số ảnh"))
        self.label_3.setText(_translate("MainWindow", "Chọn chức năng"))
        self.btn_doiTenFile.setText(_translate("MainWindow", "Đổi tên file"))
        self.btn_tangGiamNhieu.setText(_translate("MainWindow", "Tăng giảm độ nhiễu"))
        self.btn_tangGiamNet.setText(_translate("MainWindow", "Tăng giảm độ nét ảnh"))
        self.btn_giamDungLuongAnh.setText(_translate("MainWindow", "Giảm dung lượng ảnh"))
        self.btn_doiDinhDang.setText(_translate("MainWindow", "Đổi định dạng ảnh"))
        self.btn_tangGiamSang.setText(_translate("MainWindow", "Tăng giảm độ sáng"))
        self.btn_doiCoAnh.setText(_translate("MainWindow", "Đổi kích cở ảnh"))
        self.btn_chuanHoaAnh.setText(_translate("MainWindow", "Chuẩn hóa ảnh"))
        self.btn_tangGiamTuongPhan.setText(_translate("MainWindow", "Tăng giảm độ tương phản"))
        self.btn_doiHeMau.setText(_translate("MainWindow", "Đổi hệ màu"))
        self.btn_thuPhongAnh.setText(_translate("MainWindow", "Thu phóng ảnh"))
        self.btn_xoaiNghienAnh.setText(_translate("MainWindow", "Xoay, Nghiên ảnh"))
